### ISSUE TITLE
PySR should not be missed in this repository!

### ISSUE THREAD

**Issue by Evolutionary-Intelligence** [hengzhe-zhang/awesome-genetic-programming#1]
**PySR**, recently developed in **Princeton University**, should not be missed in this repository, since it has been used in many **top** journals and conferences such as **PNAS**.

**Comment by hengzhe-zhang** [comment]
I agree that PySR is a highly successful implementation of modern genetic programming techniques. There are many positive aspects that need to be studied.

**Comment by Evolutionary-Intelligence** [comment]
It has been used by some top universities such as **Harvard** (e.g., the paper *modeling the galaxy-halo connection with machine learning*). In my opinion, (wide) real-world usages are the (really) MAIN indicator for the success of one EA (in Chinese, "实践是检验真理的唯一标准"). We should include these successful application stories in our repository, since currently GP is still application-driven (of course theory is also important).

**Comment by Evolutionary-Intelligence** [comment]
Furthormore, the **commerical success** like https://www.datarobot.com/blog/eureqa-how-a-bored-undergrads-algorithm-achieved-3000-academic-citations/ is highly desriable to be included (based on GP).

**Comment by hengzhe-zhang** [comment]
Thank you very much for providing these very interesting stories. I agree that these stories can inform people about the promising future of GP. I have included them in my project.
![image](https://github.com/hengzhe-zhang/awesome-genetic-programming/assets/18747119/a2a4724f-9ca2-4f27-a5d9-27ac7f287100)
