### ISSUE TITLE
Maybe the lateset Nature paper should be added here!

### ISSUE THREAD

**Issue by Evolutionary-Intelligence** [hengzhe-zhang/awesome-genetic-programming#3]
Maybe the latest **Nature** paper involving **GP** should be added here!

**Comment by hengzhe-zhang** [comment]
Thanks for your suggestion. I have included that paper in the list. It's a wonderful paper.

![image](https://github.com/hengzhe-zhang/awesome-genetic-programming/assets/18747119/734f9f21-a602-4a02-8033-220bd3660d75)
