### ISSUE TITLE
At least William B Langdon and John Koza need to be explicitly given in **Domain Experts**

### ISSUE THREAD

**Issue by Evolutionary-Intelligence** [hengzhe-zhang/awesome-genetic-programming#4]
At least William B Langdon and John Koza need to be explicitly given in **Domain Experts**, owing to their high influences on GP.

**Comment by hengzhe-zhang** [comment]
Thank you for your comments. William B. Langdon and John Koza are experts in this domain without any doubts. I have added them to my list.
